<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>EZ2FAI</RootNamespace>
		<AssemblyName>EZ2FAI</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputPath>..\Build\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
		<NoStdLib>true</NoStdLib>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="D:\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\Mods\EZ2FAI\" />
	</Target>

	<ItemGroup>
	  <Reference Include="0Harmony">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityModManager\0Harmony.dll</HintPath>
	  </Reference>
	  <Reference Include="Accessibility">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Accessibility.dll</HintPath>
	  </Reference>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="Assembly-CSharp-firstpass">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
	  </Reference>
	  <Reference Include="DemiLib">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\DemiLib.dll</HintPath>
	  </Reference>
	  <Reference Include="DOTween">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\DOTween.dll</HintPath>
	  </Reference>
	  <Reference Include="DOTweenPro">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\DOTweenPro.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N.CJK">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.CJK.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N.MidEast">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.MidEast.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N.Other">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.Other.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N.Rare">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.Rare.dll</HintPath>
	  </Reference>
	  <Reference Include="I18N.West">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\I18N.West.dll</HintPath>
	  </Reference>
	  <Reference Include="Mono.Data.Sqlite">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Mono.Data.Sqlite.dll</HintPath>
	  </Reference>
	  <Reference Include="Mono.Posix">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Mono.Posix.dll</HintPath>
	  </Reference>
	  <Reference Include="Mono.Security">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Mono.Security.dll</HintPath>
	  </Reference>
	  <Reference Include="Mono.WebBrowser">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Mono.WebBrowser.dll</HintPath>
	  </Reference>
	  <Reference Include="mscorlib">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\mscorlib.dll</HintPath>
	  </Reference>
	  <Reference Include="netstandard">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\netstandard.dll</HintPath>
	  </Reference>
	  <Reference Include="Newtonsoft.Json">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Newtonsoft.Json.dll</HintPath>
	  </Reference>
	  <Reference Include="Novell.Directory.Ldap">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Novell.Directory.Ldap.dll</HintPath>
	  </Reference>
	  <Reference Include="Ookii.Dialogs">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Ookii.Dialogs.dll</HintPath>
	  </Reference>
	  <Reference Include="Purchasing.Common">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Purchasing.Common.dll</HintPath>
	  </Reference>
	  <Reference Include="RDTools">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\RDTools.dll</HintPath>
	  </Reference>
	  <Reference Include="Rewired_Core">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Rewired_Core.dll</HintPath>
	  </Reference>
	  <Reference Include="Rewired_Windows">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Rewired_Windows.dll</HintPath>
	  </Reference>
	  <Reference Include="Rewired_Windows_Functions">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Rewired_Windows_Functions.dll</HintPath>
	  </Reference>
	  <Reference Include="SkyHook.Unity">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\SkyHook.Unity.dll</HintPath>
	  </Reference>
	  <Reference Include="System">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Buffers">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Buffers.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Collections.Immutable">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Collections.Immutable.dll</HintPath>
	  </Reference>
	  <Reference Include="System.ComponentModel.Composition">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.ComponentModel.Composition.dll</HintPath>
	  </Reference>
	  <Reference Include="System.ComponentModel.DataAnnotations">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.ComponentModel.DataAnnotations.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Configuration">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Configuration.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Core">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Data">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Data.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Data.DataSetExtensions">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Data.DataSetExtensions.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Design">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Design.dll</HintPath>
	  </Reference>
	  <Reference Include="System.DirectoryServices">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.DirectoryServices.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Drawing">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Drawing.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Drawing.Design">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Drawing.Design.dll</HintPath>
	  </Reference>
	  <Reference Include="System.EnterpriseServices">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.EnterpriseServices.dll</HintPath>
	  </Reference>
	  <Reference Include="System.IO.Compression" />
	  <Reference Include="System.IO.Compression.FileSystem">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.IO.Compression.FileSystem.dll</HintPath>
	  </Reference>
	  <Reference Include="System.IO.Hashing">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.IO.Hashing.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Net.Http" />
	  <Reference Include="System.Numerics">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Numerics.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Numerics.Vectors">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Numerics.Vectors.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Runtime.CompilerServices.Unsafe">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Runtime.Serialization">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Runtime.Serialization.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Runtime.Serialization.Formatters.Soap">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Runtime.Serialization.Formatters.Soap.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Security">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Security.dll</HintPath>
	  </Reference>
	  <Reference Include="System.ServiceModel.Internals">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.ServiceModel.Internals.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Text.Encodings.Web">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Text.Encodings.Web.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Text.Json">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Text.Json.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Threading.Tasks.Extensions">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Threading.Tasks.Extensions.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Transactions">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Transactions.dll</HintPath>
	  </Reference>
	  <Reference Include="System.ValueTuple">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.ValueTuple.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Web">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Web.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Web.ApplicationServices">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Web.ApplicationServices.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Web.Services">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Web.Services.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Windows.Forms" />
	  <Reference Include="System.Xml">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Xml.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Xml.Linq">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\System.Xml.Linq.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Addressables">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Addressables.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Burst">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Burst.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Burst.Unsafe">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Burst.Unsafe.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Collections">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Collections.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Collections.LowLevel.ILSupport">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.InternalAPIEngineBridge.004">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.InternalAPIEngineBridge.004.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Mathematics">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Mathematics.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.MemoryProfiler">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.MemoryProfiler.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Profiling.Core">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Profiling.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.AppleMacosStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.AppleMacosStub.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.AppleStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.AppleStub.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.Codeless">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.Codeless.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.SecurityCore">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.SecurityCore.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.SecurityStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.SecurityStub.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.Stores">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.Stores.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Purchasing.Utilities">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Purchasing.Utilities.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.ResourceManager">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.ResourceManager.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.ScriptableBuildPipeline">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.ScriptableBuildPipeline.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Analytics">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Analytics.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Components">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Components.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Configuration">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Configuration.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Device">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Device.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Environments">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Environments.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Environments.Internal">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Environments.Internal.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Internal">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Internal.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Networking">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Networking.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Registration">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Registration.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Scheduler">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Scheduler.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Telemetry">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Telemetry.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Threading">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.Services.Core.Threading.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.TextMeshPro">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\Unity.TextMeshPro.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AccessibilityModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AdaptivePerformanceModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AdaptivePerformanceModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AMDModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AMDModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AndroidJNIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AnimationModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ARModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ARModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AssetBundleModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.AudioModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ClothModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ClusterInputModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ClusterRendererModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ContentLoadModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CrashReportingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.DirectorModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.DSPGraphModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.GameCenterModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.GIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.GIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.GridModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.GridModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.HierarchyCoreModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.HierarchyCoreModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.HierarchyModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.HierarchyModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.HotReloadModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.IdentifiersModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.IdentifiersModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ImageConversionModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.IMGUIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.InputForUIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.InputForUIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.InputLegacyModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.InputModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.InputModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.InsightsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.InsightsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.JSONSerializeModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.LocalizationModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.MarshallingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.MarshallingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.MultiplayerModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.MultiplayerModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.NVIDIAModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ParticleSystemModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.PerformanceReportingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Physics2DModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.PhysicsBackendPhysXModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.PhysicsBackendPhysXModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.PhysicsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ProfilerModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.PropertiesModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.AppleCore">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.AppleCore.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.AppleMacosStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.AppleMacosStub.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.AppleStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.AppleStub.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.Codeless">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.Codeless.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.SecurityCore">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.SecurityCore.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.SecurityStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.SecurityStub.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.Stores">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.Stores.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.WinRTCore">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.WinRTCore.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.Purchasing.WinRTStub">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.Purchasing.WinRTStub.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.RenderAs2DModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.RenderAs2DModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ScreenCaptureModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ShaderRuntimeModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ShaderRuntimeModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.SharedInternalsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.SpriteMaskModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.SpriteShapeModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.StreamingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.SubstanceModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.SubsystemsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TerrainModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TerrainPhysicsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TextCoreFontEngineModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TextCoreTextEngineModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TextRenderingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TilemapModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TLSModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UI">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UI.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UIElementsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UIModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UmbraModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityAnalyticsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityConnectModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityConsentModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityConsentModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityCurlModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityTestProtocolModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestAudioModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestTextureModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestWWWModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VectorGraphicsModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VectorGraphicsModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VehiclesModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VFXModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VideoModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VirtualTexturingModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.VRModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.VRModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.WindModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.WindModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.XRModule">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityEngine.XRModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityFileDialog">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityFileDialog.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityModManager">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\UnityModManager\UnityModManager.dll</HintPath>
	  </Reference>
	  <Reference Include="XTUtilities">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed\XTUtilities.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>